# Generated by Django 6.0.3 on 2026-03-10 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('indication', models.CharField(max_length=255)),
                ('clinical_details', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('motion_risk', models.CharField(max_length=50)),
                ('claustrophobia', models.BooleanField(default=False)),
                ('renal_status', models.CharField(max_length=100)),
                ('has_implant', models.BooleanField(default=False)),
                ('field_strength', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=100)),
                ('selected_coils', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='protocols.region')),
            ],
            options={
                'unique_together': {('region', 'name')},
            },
        ),
    ]
