# Generated by Django 6.0.2 on 2026-03-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_details', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('motion_risk', models.CharField(max_length=50)),
                ('claustrophobia', models.BooleanField(default=False)),
                ('renal_status', models.CharField(max_length=100)),
                ('has_implant', models.BooleanField(default=False)),
                ('field_strength', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=100)),
                ('selected_coils', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocols.indication')),
            ],
        ),
    ]
