# Generated by Django 6.0.2 on 2026-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocolrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolrequest',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='indication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
