# Generated by Django 6.0.3 on 2026-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_alter_savedprotocol_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolrequest',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='field_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='motion_risk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='renal_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
