# Generated by Django 6.0.3 on 2026-03-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0006_alter_protocolrequest_age_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedprotocol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to=settings.AUTH_USER_MODEL),
        ),
    ]
