# Generated by Django 6.0.3 on 2026-03-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hospital_name',
            new_name='hospital_id',
        ),
    ]
